name: Check latest status date
on:
  schedule:
    - cron: "26 10 * * 4"  # Set to run every Thursdays
jobs:
  latest-status:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements-dev.txt
      - name: Run tests
        run: venv/bin/pytest tests/check_latest_status.py
