name: Check latest status date
on:
  schedule:
    - cron: "26 10 * * 4"  # Set to run every Thursdays
jobs:
  latest-status:
    runs-on: python:3.12.6-slim-bookworm
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest tests/test_latest_status.py
