name: Run tests
on:
  push:
  schedule:
    - cron: "47 7 2 * *"  # Set to run monthly
jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements-dev.txt
          pip install .
      - name: Run tests
        run: venv/bin/pytest tests
